# Generated by Django 5.2.9 on 2026-05-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_content_images/', verbose_name='본문 사진'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='위치정보'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=300, verbose_name='태그'),
        ),
    ]
