# Generated by Django 5.2.9 on 2026-05-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_content_image_post_location_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='program_file',
            field=models.FileField(blank=True, null=True, upload_to='post_program_files/', verbose_name='첨부 프로그램'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='썸네일 문구'),
        ),
    ]
