# Generated by Django 5.2.9 on 2026-05-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_program_file_post_thumbnail_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/', verbose_name='본문 동영상'),
        ),
    ]
