# Generated by Django 5.2.9 on 2026-05-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_userprofile_slug_post_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='경험창고 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='AI 글 생성에 사용')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '경험창고',
                'verbose_name_plural': '경험창고',
            },
        ),
    ]
