# Generated by Django 5.2.9 on 2026-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_experiencevault'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_visitl_created_57350e_idx'), models.Index(fields=['visitor_key'], name='core_visitl_visitor_cf319e_idx'), models.Index(fields=['path'], name='core_visitl_path_ba0c0f_idx')],
            },
        ),
    ]
