# Generated by Django 5.2.9 on 2026-06-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visitlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutoWriterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='자동 생성 실행 여부')),
                ('interval_minutes', models.PositiveIntegerField(choices=[(10, '10분마다 1개'), (30, '30분마다 1개'), (60, '1시간마다 1개'), (120, '2시간마다 1개')], default=30, verbose_name='자동 생성 간격')),
                ('keyword_count_per_category', models.PositiveIntegerField(default=7, verbose_name='카테고리별 추천키워드 수')),
                ('publish_immediately', models.BooleanField(default=True, verbose_name='생성 후 바로 공개')),
                ('daily_limit', models.PositiveIntegerField(default=30, verbose_name='하루 최대 생성 글 수')),
                ('use_architecture', models.BooleanField(default=True, verbose_name='건축 사용')),
                ('use_realestate', models.BooleanField(default=True, verbose_name='부동산 사용')),
                ('use_finance', models.BooleanField(default=True, verbose_name='금융 사용')),
                ('use_tech', models.BooleanField(default=True, verbose_name='테크 사용')),
                ('use_life', models.BooleanField(default=True, verbose_name='일상 사용')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 실행 시간')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='다음 실행 예정 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'AI 자동글 생성 설정',
                'verbose_name_plural': 'AI 자동글 생성 설정',
            },
        ),
        migrations.CreateModel(
            name='AIAutoKeywordQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('architecture', '건축'), ('realestate', '부동산'), ('finance', '금융'), ('tech', '테크'), ('life', '일상')], max_length=30, verbose_name='카테고리')),
                ('keyword', models.CharField(max_length=200, verbose_name='추천키워드')),
                ('status', models.CharField(choices=[('waiting', '대기'), ('processing', '생성 중'), ('done', '완료'), ('failed', '실패')], default='waiting', max_length=20, verbose_name='상태')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='생성 순서')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='대기열 등록일')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='생성 시작 시간')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='생성 완료 시간')),
                ('generated_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_auto_keyword_items', to='core.post', verbose_name='생성된 글')),
            ],
            options={
                'verbose_name': 'AI 자동글 키워드 대기열',
                'verbose_name_plural': 'AI 자동글 키워드 대기열',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
