# Generated by Django 5.2.9 on 2026-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aiautowritersetting_aiautokeywordqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiautokeywordqueue',
            name='news_context',
            field=models.TextField(blank=True, default='', verbose_name='뉴스 기반 참고 내용'),
        ),
        migrations.AddField(
            model_name='aiautokeywordqueue',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='추천 이유 / 관련 뉴스 요약'),
        ),
    ]
