# Generated by Django 5.2.9 on 2026-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aiautokeywordqueue_news_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiautowritersetting',
            name='include_tags',
            field=models.BooleanField(default=True, verbose_name='태그 자동 생성'),
        ),
        migrations.AddField(
            model_name='aiautowritersetting',
            name='make_thumbnail',
            field=models.BooleanField(default=False, verbose_name='대표 썸네일 이미지 자동 생성'),
        ),
    ]
