# Generated by Django 5.2.9 on 2026-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aiautowritersetting_include_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiautowritersetting',
            name='image_count',
            field=models.PositiveIntegerField(default=0, verbose_name='본문 이미지 개수'),
        ),
    ]
