# Generated by Django 5.2.9 on 2026-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aiautowritersetting_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shorts_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='shorts_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='shorts_status',
            field=models.CharField(blank=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='shorts_video',
            field=models.FileField(blank=True, null=True, upload_to='shorts/'),
        ),
    ]
