# Generated by Django 5.2.9 on 2026-06-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post_shorts_created_at_post_shorts_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shorts_cover',
            field=models.ImageField(blank=True, null=True, upload_to='shorts_covers/'),
        ),
    ]
