# Generated by Django 5.2.9 on 2026-06-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_post_shorts_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCapcutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='프로젝트명')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='편집 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_capcut_projects', to='core.post', verbose_name='연결 글')),
            ],
            options={
                'verbose_name': '미니 CapCut 프로젝트',
                'verbose_name_plural': '미니 CapCut 프로젝트',
            },
        ),
    ]
