# Generated by Django 5.2.9 on 2026-06-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_post_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='프로그램 식별자')),
                ('name', models.CharField(max_length=120, verbose_name='프로그램명')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='설명')),
                ('mac_file', models.FileField(blank=True, null=True, upload_to='program_downloads/mac/', verbose_name='Mac용 파일')),
                ('windows_file', models.FileField(blank=True, null=True, upload_to='program_downloads/windows/', verbose_name='Windows용 파일')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '프로그램 다운로드',
                'verbose_name_plural': '프로그램 다운로드',
                'ordering': ['order', 'id'],
            },
        ),
    ]
