# Generated by Django 5.2.9 on 2026-06-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_programdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='일정명')),
                ('event_date', models.DateField(verbose_name='일정 날짜')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('category', models.CharField(blank=True, default='일정', help_text='예: 업데이트, 강의, 배포, 공지, 개인일정', max_length=30, verbose_name='분류')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('link_url', models.URLField(blank=True, verbose_name='연결 링크')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요 일정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '주요 일정',
                'verbose_name_plural': '주요 일정',
                'ordering': ['event_date', 'start_time', 'id'],
            },
        ),
    ]
