# Generated by Django 5.2.9 on 2026-06-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료 날짜'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_date',
            field=models.DateField(verbose_name='시작 날짜'),
        ),
    ]
