# Generated by CBL construction category patch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_calendarevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_construction_tech',
            field=models.BooleanField(default=True, verbose_name='건설기술 사용'),
        ),
    ]
