# Generated by Django 5.2.9 on 2026-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_aiautowritersetting_use_construction_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('question', '질문/답변'), ('error', '오류 제보'), ('request', '프로그램 요청'), ('faq', '자주하는 질문')], default='question', max_length=30, verbose_name='분류')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='문의 내용')),
                ('author_name', models.CharField(blank=True, default='익명', max_length=40, verbose_name='작성자')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='연락처/이메일')),
                ('answer', models.TextField(blank=True, verbose_name='답변')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
            ],
            options={
                'verbose_name': '커뮤니티 문의',
                'verbose_name_plural': '커뮤니티 문의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='aiautokeywordqueue',
            name='category',
            field=models.CharField(choices=[('construction_work', '건설실무'), ('construction_tech', '건설기술'), ('bim', 'BIM'), ('construction_real', '건설부동산'), ('finance', '금융'), ('tech', '테크'), ('program', '프로그램'), ('life', '일상'), ('architecture', '건축'), ('realestate', '부동산')], max_length=30, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='aiautowritersetting',
            name='use_architecture',
            field=models.BooleanField(default=True, verbose_name='건설실무 사용'),
        ),
        migrations.AlterField(
            model_name='aiautowritersetting',
            name='use_realestate',
            field=models.BooleanField(default=True, verbose_name='건설부동산 사용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('construction_work', '건설실무'), ('construction_tech', '건설기술'), ('bim', 'BIM'), ('construction_real', '건설부동산'), ('finance', '금융'), ('tech', '테크'), ('program', '프로그램'), ('life', '일상'), ('architecture', '건축'), ('realestate', '부동산')], max_length=20, verbose_name='카테고리'),
        ),
    ]
