# Generated by Django 5.2.9 on 2026-06-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_communityquestion_alter_aiautokeywordqueue_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_bim',
            field=models.BooleanField(default=True, verbose_name='REVIT/BIM 사용'),
        ),
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_dynamo_automation',
            field=models.BooleanField(default=True, verbose_name='Dynamo/자동화 사용'),
        ),
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_four_d_five_d',
            field=models.BooleanField(default=True, verbose_name='4D/5D 사용'),
        ),
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_program',
            field=models.BooleanField(default=True, verbose_name='업무용 프로그램 사용'),
        ),
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_tool_recommend',
            field=models.BooleanField(default=True, verbose_name='툴소개/툴추천 사용'),
        ),
        migrations.AlterField(
            model_name='aiautokeywordqueue',
            name='category',
            field=models.CharField(choices=[('construction_work', '건설실무'), ('construction_tech', '건설기술'), ('construction_real', '건설부동산'), ('bim', 'REVIT/BIM'), ('dynamo_automation', 'Dynamo/자동화'), ('four_d_five_d', '4D/5D'), ('program', '업무용 프로그램'), ('tool_recommend', '툴소개/툴추천'), ('architecture', '건축'), ('realestate', '부동산'), ('finance', '금융'), ('tech', '테크'), ('life', '일상')], max_length=30, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('construction_work', '건설실무'), ('construction_tech', '건설기술'), ('construction_real', '건설부동산'), ('bim', 'REVIT/BIM'), ('dynamo_automation', 'Dynamo/자동화'), ('four_d_five_d', '4D/5D'), ('program', '업무용 프로그램'), ('tool_recommend', '툴소개/툴추천'), ('architecture', '건축'), ('realestate', '부동산'), ('finance', '금융'), ('tech', '테크'), ('life', '일상')], max_length=20, verbose_name='카테고리'),
        ),
    ]
