# Generated by Django 5.2.9 on 2026-06-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_programdownload_public_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProgramDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='표시명')),
                ('badge', models.CharField(blank=True, default='', max_length=20, verbose_name='짧은 라벨')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='설명')),
                ('file', models.FileField(blank=True, null=True, upload_to='home_programs/', verbose_name='다운로드 파일')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '홈 인기 프로그램',
                'verbose_name_plural': '홈 인기 프로그램',
                'ordering': ['order', 'id'],
            },
        ),
    ]
