# Generated by Django 5.2.9 on 2026-06-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_homeprogramdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='event_color',
            field=models.CharField(default='#2f9e97', max_length=7, verbose_name='이벤트 바 색상'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_all_day',
            field=models.BooleanField(default=False, verbose_name='온종일'),
        ),
    ]
