# Generated by Django 5.2.9 on 2026-07-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_post_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_tech_ai_development',
            field=models.BooleanField(default=True, verbose_name='AI·개발 사용'),
        ),
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_tech_data_security',
            field=models.BooleanField(default=True, verbose_name='데이터·보안 사용'),
        ),
        migrations.AddField(
            model_name='aiautowritersetting',
            name='use_tech_server_software',
            field=models.BooleanField(default=True, verbose_name='인터넷·서버·소프트 사용'),
        ),
        migrations.AlterField(
            model_name='aiautokeywordqueue',
            name='category',
            field=models.CharField(choices=[('construction_work', '건설실무'), ('construction_tech', '건설기술'), ('construction_real', '건설부동산'), ('bim', 'REVIT/BIM'), ('dynamo_automation', 'Dynamo/자동화'), ('four_d_five_d', '4D/5D'), ('tech_ai_development', 'AI·개발'), ('tech_data_security', '데이터·보안'), ('tech_server_software', '인터넷·서버·소프트'), ('program', '업무용 프로그램'), ('tool_recommend', '툴소개/툴추천'), ('architecture', '건축'), ('realestate', '부동산'), ('finance', '금융'), ('tech', '테크'), ('life', '일상')], max_length=30, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('construction_work', '건설실무'), ('construction_tech', '건설기술'), ('construction_real', '건설부동산'), ('bim', 'REVIT/BIM'), ('dynamo_automation', 'Dynamo/자동화'), ('four_d_five_d', '4D/5D'), ('tech_ai_development', 'AI·개발'), ('tech_data_security', '데이터·보안'), ('tech_server_software', '인터넷·서버·소프트'), ('program', '업무용 프로그램'), ('tool_recommend', '툴소개/툴추천'), ('architecture', '건축'), ('realestate', '부동산'), ('finance', '금융'), ('tech', '테크'), ('life', '일상')], max_length=20, verbose_name='카테고리'),
        ),
    ]
