# Generated by Django 5.2.9 on 2026-08-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_ai_fallback_topic_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdownload',
            name='mac_download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Mac 다운로드 수'),
        ),
        migrations.AddField(
            model_name='programdownload',
            name='windows_download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Windows 다운로드 수'),
        ),
    ]
