# Generated by Django 5.2.9 on 2026-08-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_program_download_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeprogramdownload',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='다운로드 수'),
        ),
    ]
