# Generated by Django 5.2.9 on 2026-08-02 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_home_program_download_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, verbose_name='관심 분야'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False, verbose_name='마케팅 정보 수신 동의'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
    ]
